namespace Utilities.Infrastructure.UtilityInfrastructure.Operations
{
    public static class NameOperation
    {
        public static string CharacterRegulatory(string name)
           => name.Replace("\"", string.Empty)
               .Replace("!", string.Empty)
               .Replace("'", string.Empty)
               .Replace("^", string.Empty)
               .Replace("+", string.Empty)
               .Replace("%", string.Empty)
               .Replace("&", string.Empty)
               .Replace("/", string.Empty)
               .Replace("(", string.Empty)
               .Replace(")", string.Empty)
               .Replace("=", string.Empty)
               .Replace("?", string.Empty)
               .Replace("_", string.Empty)
               .Replace(" ", "-")
               .Replace("@", string.Empty)
               .Replace("€", string.Empty)
               .Replace("¨", string.Empty)
               .Replace("~", string.Empty)
               .Replace(",", string.Empty)
               .Replace(";", string.Empty)
               .Replace(":", string.Empty)
               .Replace(".", "-")
               .Replace("Ö", "o")
               .Replace("ö", "o")
               .Replace("Ü", "u")
               .Replace("ü", "u")
               .Replace("ı", "i")
               .Replace("İ", "i")
               .Replace("ğ", "g")
               .Replace("Ğ", "g")
               .Replace("æ", string.Empty)
               .Replace("ß", string.Empty)
               .Replace("â", "a")
               .Replace("î", "i")
               .Replace("ş", "s")
               .Replace("Ş", "s")
               .Replace("Ç", "c")
               .Replace("ç", "c")
               .Replace("<", string.Empty)
               .Replace(">", string.Empty)
               .Replace("|", string.Empty);
    }
}
