//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VakifBankVPosTest
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PayFlexVPosWebService", ConfigurationName="VakifBankVPosTest.TransactionWebServicesSoap")]
    public interface TransactionWebServicesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="PayFlexVPosWebService/ExecuteVposRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VakifBankVPosTest.VposResponse> ExecuteVposRequestAsync(VakifBankVPosTest.VposRequest vposRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class VposRequest
    {
        
        private string merchantIdField;
        
        private string identityField;
        
        private string passwordField;
        
        private string terminalNoField;
        
        private string transactionTypeField;
        
        private string apiTransactionTypeField;
        
        private string transactionIdField;
        
        private string referenceTransactionIdField;
        
        private System.Nullable<int> numberOfInstallmentsField;
        
        private bool numberOfInstallmentsFieldSpecified;
        
        private System.Nullable<decimal> currencyAmountField;
        
        private bool currencyAmountFieldSpecified;
        
        private System.Nullable<decimal> amountShareField;
        
        private bool amountShareFieldSpecified;
        
        private System.Nullable<decimal> surchargeAmountField;
        
        private bool surchargeAmountFieldSpecified;
        
        private System.Nullable<int> currencyCodeField;
        
        private bool currencyCodeFieldSpecified;
        
        private System.Nullable<decimal> pointAmountField;
        
        private bool pointAmountFieldSpecified;
        
        private System.Nullable<decimal> totalPointAmountField;
        
        private bool totalPointAmountFieldSpecified;
        
        private System.Nullable<int> pointCodeField;
        
        private bool pointCodeFieldSpecified;
        
        private string panField;
        
        private string cardNoFirstField;
        
        private string cardNoLastField;
        
        private string installmentCountField;
        
        private string inquiryValueField;
        
        private string cvvField;
        
        private string securityCodeField;
        
        private string expiryField;
        
        private System.Nullable<int> locationField;
        
        private bool locationFieldSpecified;
        
        private string extractField;
        
        private System.Nullable<int> deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private string tAVVField;
        
        private string cardHoldersNameField;
        
        private string clientIpField;
        
        private string merchantIpField;
        
        private string cardHoldersEmailField;
        
        private string orderIdField;
        
        private string orderDescriptionField;
        
        private string triggerDateField;
        
        private System.Nullable<bool> isRecurringField;
        
        private bool isRecurringFieldSpecified;
        
        private System.Nullable<bool> isInvoiceField;
        
        private bool isInvoiceFieldSpecified;
        
        private string recurringFrequencyTypeField;
        
        private System.Nullable<int> recurringFrequencyField;
        
        private bool recurringFrequencyFieldSpecified;
        
        private System.Nullable<int> recurringInstallmentCountField;
        
        private bool recurringInstallmentCountFieldSpecified;
        
        private string mpiTransactionIdField;
        
        private string expSignField;
        
        private string cAVVField;
        
        private string eCIField;
        
        private Item[] customItemsField;
        
        private CustomInstallments customInstallmentsField;
        
        private string brandNameField;
        
        private string panMaskedField;
        
        private string cvvMaskedField;
        
        private System.Nullable<int> transactionDeviceSourceField;
        
        private bool transactionDeviceSourceFieldSpecified;
        
        private string securityCodeMaskedField;
        
        private string customerNumberField;
        
        private string customerNameField;
        
        private string panCodeField;
        
        private string hostSubMerchantIdField;
        
        private System.Nullable<int> merchantTypeField;
        
        private bool merchantTypeFieldSpecified;
        
        private System.Nullable<int> transactionSourceField;
        
        private bool transactionSourceFieldSpecified;
        
        private System.Nullable<bool> includeHostResultCodeField;
        
        private bool includeHostResultCodeFieldSpecified;
        
        private CampaignInfo[] campaignResultField;
        
        private string storeNoField;
        
        private System.Nullable<int> transactionChannelField;
        
        private System.Nullable<bool> isTriggeredByBatchCloseFlowField;
        
        private string bKHesapNoField;
        
        private string bKUrunKoduField;
        
        private string hKUrunKoduField;
        
        private string hKPlasiyerNoField;
        
        private string hKFaturaNoField;
        
        private string hKVadeKoduField;
        
        private int hKVadeAdediField;
        
        private string hKVadeBilgiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantId
        {
            get
            {
                return this.merchantIdField;
            }
            set
            {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TerminalNo
        {
            get
            {
                return this.terminalNoField;
            }
            set
            {
                this.terminalNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ApiTransactionType
        {
            get
            {
                return this.apiTransactionTypeField;
            }
            set
            {
                this.apiTransactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TransactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ReferenceTransactionId
        {
            get
            {
                return this.referenceTransactionIdField;
            }
            set
            {
                this.referenceTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> NumberOfInstallments
        {
            get
            {
                return this.numberOfInstallmentsField;
            }
            set
            {
                this.numberOfInstallmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfInstallmentsSpecified
        {
            get
            {
                return this.numberOfInstallmentsFieldSpecified;
            }
            set
            {
                this.numberOfInstallmentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> CurrencyAmount
        {
            get
            {
                return this.currencyAmountField;
            }
            set
            {
                this.currencyAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyAmountSpecified
        {
            get
            {
                return this.currencyAmountFieldSpecified;
            }
            set
            {
                this.currencyAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> AmountShare
        {
            get
            {
                return this.amountShareField;
            }
            set
            {
                this.amountShareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountShareSpecified
        {
            get
            {
                return this.amountShareFieldSpecified;
            }
            set
            {
                this.amountShareFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> SurchargeAmount
        {
            get
            {
                return this.surchargeAmountField;
            }
            set
            {
                this.surchargeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SurchargeAmountSpecified
        {
            get
            {
                return this.surchargeAmountFieldSpecified;
            }
            set
            {
                this.surchargeAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> CurrencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyCodeSpecified
        {
            get
            {
                return this.currencyCodeFieldSpecified;
            }
            set
            {
                this.currencyCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> PointAmount
        {
            get
            {
                return this.pointAmountField;
            }
            set
            {
                this.pointAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointAmountSpecified
        {
            get
            {
                return this.pointAmountFieldSpecified;
            }
            set
            {
                this.pointAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<decimal> TotalPointAmount
        {
            get
            {
                return this.totalPointAmountField;
            }
            set
            {
                this.totalPointAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPointAmountSpecified
        {
            get
            {
                return this.totalPointAmountFieldSpecified;
            }
            set
            {
                this.totalPointAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> PointCode
        {
            get
            {
                return this.pointCodeField;
            }
            set
            {
                this.pointCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointCodeSpecified
        {
            get
            {
                return this.pointCodeFieldSpecified;
            }
            set
            {
                this.pointCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Pan
        {
            get
            {
                return this.panField;
            }
            set
            {
                this.panField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CardNoFirst
        {
            get
            {
                return this.cardNoFirstField;
            }
            set
            {
                this.cardNoFirstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CardNoLast
        {
            get
            {
                return this.cardNoLastField;
            }
            set
            {
                this.cardNoLastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string InstallmentCount
        {
            get
            {
                return this.installmentCountField;
            }
            set
            {
                this.installmentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string InquiryValue
        {
            get
            {
                return this.inquiryValueField;
            }
            set
            {
                this.inquiryValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Cvv
        {
            get
            {
                return this.cvvField;
            }
            set
            {
                this.cvvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string SecurityCode
        {
            get
            {
                return this.securityCodeField;
            }
            set
            {
                this.securityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Expiry
        {
            get
            {
                return this.expiryField;
            }
            set
            {
                this.expiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<int> Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationSpecified
        {
            get
            {
                return this.locationFieldSpecified;
            }
            set
            {
                this.locationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Extract
        {
            get
            {
                return this.extractField;
            }
            set
            {
                this.extractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<int> DeviceType
        {
            get
            {
                return this.deviceTypeField;
            }
            set
            {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceTypeSpecified
        {
            get
            {
                return this.deviceTypeFieldSpecified;
            }
            set
            {
                this.deviceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string TAVV
        {
            get
            {
                return this.tAVVField;
            }
            set
            {
                this.tAVVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string CardHoldersName
        {
            get
            {
                return this.cardHoldersNameField;
            }
            set
            {
                this.cardHoldersNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string ClientIp
        {
            get
            {
                return this.clientIpField;
            }
            set
            {
                this.clientIpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string MerchantIp
        {
            get
            {
                return this.merchantIpField;
            }
            set
            {
                this.merchantIpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string CardHoldersEmail
        {
            get
            {
                return this.cardHoldersEmailField;
            }
            set
            {
                this.cardHoldersEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string OrderDescription
        {
            get
            {
                return this.orderDescriptionField;
            }
            set
            {
                this.orderDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string TriggerDate
        {
            get
            {
                return this.triggerDateField;
            }
            set
            {
                this.triggerDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<bool> IsRecurring
        {
            get
            {
                return this.isRecurringField;
            }
            set
            {
                this.isRecurringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsRecurringSpecified
        {
            get
            {
                return this.isRecurringFieldSpecified;
            }
            set
            {
                this.isRecurringFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<bool> IsInvoice
        {
            get
            {
                return this.isInvoiceField;
            }
            set
            {
                this.isInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsInvoiceSpecified
        {
            get
            {
                return this.isInvoiceFieldSpecified;
            }
            set
            {
                this.isInvoiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string RecurringFrequencyType
        {
            get
            {
                return this.recurringFrequencyTypeField;
            }
            set
            {
                this.recurringFrequencyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<int> RecurringFrequency
        {
            get
            {
                return this.recurringFrequencyField;
            }
            set
            {
                this.recurringFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurringFrequencySpecified
        {
            get
            {
                return this.recurringFrequencyFieldSpecified;
            }
            set
            {
                this.recurringFrequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public System.Nullable<int> RecurringInstallmentCount
        {
            get
            {
                return this.recurringInstallmentCountField;
            }
            set
            {
                this.recurringInstallmentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurringInstallmentCountSpecified
        {
            get
            {
                return this.recurringInstallmentCountFieldSpecified;
            }
            set
            {
                this.recurringInstallmentCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string MpiTransactionId
        {
            get
            {
                return this.mpiTransactionIdField;
            }
            set
            {
                this.mpiTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string ExpSign
        {
            get
            {
                return this.expSignField;
            }
            set
            {
                this.expSignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string CAVV
        {
            get
            {
                return this.cAVVField;
            }
            set
            {
                this.cAVVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string ECI
        {
            get
            {
                return this.eCIField;
            }
            set
            {
                this.eCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=44)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Item[] CustomItems
        {
            get
            {
                return this.customItemsField;
            }
            set
            {
                this.customItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public CustomInstallments CustomInstallments
        {
            get
            {
                return this.customInstallmentsField;
            }
            set
            {
                this.customInstallmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string BrandName
        {
            get
            {
                return this.brandNameField;
            }
            set
            {
                this.brandNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string PanMasked
        {
            get
            {
                return this.panMaskedField;
            }
            set
            {
                this.panMaskedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string CvvMasked
        {
            get
            {
                return this.cvvMaskedField;
            }
            set
            {
                this.cvvMaskedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public System.Nullable<int> TransactionDeviceSource
        {
            get
            {
                return this.transactionDeviceSourceField;
            }
            set
            {
                this.transactionDeviceSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDeviceSourceSpecified
        {
            get
            {
                return this.transactionDeviceSourceFieldSpecified;
            }
            set
            {
                this.transactionDeviceSourceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string SecurityCodeMasked
        {
            get
            {
                return this.securityCodeMaskedField;
            }
            set
            {
                this.securityCodeMaskedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string CustomerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string PanCode
        {
            get
            {
                return this.panCodeField;
            }
            set
            {
                this.panCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string HostSubMerchantId
        {
            get
            {
                return this.hostSubMerchantIdField;
            }
            set
            {
                this.hostSubMerchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=55)]
        public System.Nullable<int> MerchantType
        {
            get
            {
                return this.merchantTypeField;
            }
            set
            {
                this.merchantTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantTypeSpecified
        {
            get
            {
                return this.merchantTypeFieldSpecified;
            }
            set
            {
                this.merchantTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=56)]
        public System.Nullable<int> TransactionSource
        {
            get
            {
                return this.transactionSourceField;
            }
            set
            {
                this.transactionSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionSourceSpecified
        {
            get
            {
                return this.transactionSourceFieldSpecified;
            }
            set
            {
                this.transactionSourceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=57)]
        public System.Nullable<bool> IncludeHostResultCode
        {
            get
            {
                return this.includeHostResultCodeField;
            }
            set
            {
                this.includeHostResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeHostResultCodeSpecified
        {
            get
            {
                return this.includeHostResultCodeFieldSpecified;
            }
            set
            {
                this.includeHostResultCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=58)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CampaignItem", IsNullable=false)]
        public CampaignInfo[] CampaignResult
        {
            get
            {
                return this.campaignResultField;
            }
            set
            {
                this.campaignResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string StoreNo
        {
            get
            {
                return this.storeNoField;
            }
            set
            {
                this.storeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=60)]
        public System.Nullable<int> TransactionChannel
        {
            get
            {
                return this.transactionChannelField;
            }
            set
            {
                this.transactionChannelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=61)]
        public System.Nullable<bool> IsTriggeredByBatchCloseFlow
        {
            get
            {
                return this.isTriggeredByBatchCloseFlowField;
            }
            set
            {
                this.isTriggeredByBatchCloseFlowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string BKHesapNo
        {
            get
            {
                return this.bKHesapNoField;
            }
            set
            {
                this.bKHesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string BKUrunKodu
        {
            get
            {
                return this.bKUrunKoduField;
            }
            set
            {
                this.bKUrunKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string HKUrunKodu
        {
            get
            {
                return this.hKUrunKoduField;
            }
            set
            {
                this.hKUrunKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string HKPlasiyerNo
        {
            get
            {
                return this.hKPlasiyerNoField;
            }
            set
            {
                this.hKPlasiyerNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string HKFaturaNo
        {
            get
            {
                return this.hKFaturaNoField;
            }
            set
            {
                this.hKFaturaNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string HKVadeKodu
        {
            get
            {
                return this.hKVadeKoduField;
            }
            set
            {
                this.hKVadeKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public int HKVadeAdedi
        {
            get
            {
                return this.hKVadeAdediField;
            }
            set
            {
                this.hKVadeAdediField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string HKVadeBilgi
        {
            get
            {
                return this.hKVadeBilgiField;
            }
            set
            {
                this.hKVadeBilgiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class Item
    {
        
        private string nameField;
        
        private string valueField;
        
        private string customTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string customType
        {
            get
            {
                return this.customTypeField;
            }
            set
            {
                this.customTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class BKSaleInfo
    {
        
        private string expiryDateField;
        
        private string productDescField;
        
        private string numberOfDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string productDesc
        {
            get
            {
                return this.productDescField;
            }
            set
            {
                this.productDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string numberOfDays
        {
            get
            {
                return this.numberOfDaysField;
            }
            set
            {
                this.numberOfDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class BKAccountKonuLimit
    {
        
        private System.Nullable<decimal> limitField;
        
        private bool limitFieldSpecified;
        
        private string konuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> Limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LimitSpecified
        {
            get
            {
                return this.limitFieldSpecified;
            }
            set
            {
                this.limitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Konu
        {
            get
            {
                return this.konuField;
            }
            set
            {
                this.konuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class BKAccount
    {
        
        private BKAccountKonuLimit[] bKKonuLimitsField;
        
        private string hesapNoField;
        
        private string hesapAdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public BKAccountKonuLimit[] BKKonuLimits
        {
            get
            {
                return this.bKKonuLimitsField;
            }
            set
            {
                this.bKKonuLimitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HesapNo
        {
            get
            {
                return this.hesapNoField;
            }
            set
            {
                this.hesapNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HesapAdi
        {
            get
            {
                return this.hesapAdiField;
            }
            set
            {
                this.hesapAdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class PlanSearchResult
    {
        
        private int maturityPeriodField;
        
        private int frequencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maturityPeriod
        {
            get
            {
                return this.maturityPeriodField;
            }
            set
            {
                this.maturityPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int frequency
        {
            get
            {
                return this.frequencyField;
            }
            set
            {
                this.frequencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class LimitSearchResult
    {
        
        private string typeField;
        
        private decimal limitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class MerchantCampaignResult
    {
        
        private string hostResponseCodeField;
        
        private string hostResponseMessageField;
        
        private CampaignInfo[] campaignInfosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HostResponseCode
        {
            get
            {
                return this.hostResponseCodeField;
            }
            set
            {
                this.hostResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HostResponseMessage
        {
            get
            {
                return this.hostResponseMessageField;
            }
            set
            {
                this.hostResponseMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public CampaignInfo[] CampaignInfos
        {
            get
            {
                return this.campaignInfosField;
            }
            set
            {
                this.campaignInfosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class CampaignInfo
    {
        
        private string actionField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string extradescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extradescription
        {
            get
            {
                return this.extradescriptionField;
            }
            set
            {
                this.extradescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class InstallmentItem
    {
        
        private string dateField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class VposResponse
    {
        
        private string merchantIdField;
        
        private string transactionTypeField;
        
        private string transactionIdField;
        
        private string referenceTransactionIdField;
        
        private string resultCodeField;
        
        private string resultDetailField;
        
        private Item[] customItemsField;
        
        private InstallmentItem[] installmentTableField;
        
        private CampaignInfo[] campaignResultField;
        
        private MerchantCampaignResult merchantCampaignResultField;
        
        private string authCodeField;
        
        private string hostDateField;
        
        private string rrnField;
        
        private System.Nullable<decimal> pointLostsField;
        
        private bool pointLostsFieldSpecified;
        
        private string terminalNoField;
        
        private System.Nullable<decimal> pointAmountField;
        
        private bool pointAmountFieldSpecified;
        
        private System.Nullable<int> pointCodeField;
        
        private bool pointCodeFieldSpecified;
        
        private System.Nullable<decimal> gainedPointField;
        
        private bool gainedPointFieldSpecified;
        
        private System.Nullable<decimal> totalPointField;
        
        private bool totalPointFieldSpecified;
        
        private System.Nullable<decimal> currencyAmountField;
        
        private bool currencyAmountFieldSpecified;
        
        private System.Nullable<int> currencyCodeField;
        
        private bool currencyCodeFieldSpecified;
        
        private System.Nullable<decimal> vftAmountField;
        
        private bool vftAmountFieldSpecified;
        
        private System.Nullable<decimal> surchargeAmountField;
        
        private bool surchargeAmountFieldSpecified;
        
        private System.Nullable<int> numberOfInstallmentsField;
        
        private bool numberOfInstallmentsFieldSpecified;
        
        private System.Nullable<int> installmentCountField;
        
        private bool installmentCountFieldSpecified;
        
        private System.Nullable<int> recurringInstallmentCountField;
        
        private bool recurringInstallmentCountFieldSpecified;
        
        private string orderIdField;
        
        private string eCIField;
        
        private System.Nullable<int> threeDSecureTypeField;
        
        private bool threeDSecureTypeFieldSpecified;
        
        private System.Nullable<int> transactionDeviceSourceField;
        
        private bool transactionDeviceSourceFieldSpecified;
        
        private System.Nullable<int> locationField;
        
        private bool locationFieldSpecified;
        
        private System.Nullable<int> deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private string tavvField;
        
        private System.Nullable<int> batchNoField;
        
        private bool batchNoFieldSpecified;
        
        private string panCodeField;
        
        private System.Nullable<decimal> tLAmountField;
        
        private bool tLAmountFieldSpecified;
        
        private LimitSearchResult[] limitSearchResultsField;
        
        private PlanSearchResult[] planSearchResultsField;
        
        private string hostSubMerchantIdField;
        
        private string identityField;
        
        private System.Nullable<int> merchantTypeField;
        
        private bool merchantTypeFieldSpecified;
        
        private string hostResultCodeField;
        
        private BKAccount[] bKAccountsField;
        
        private BKSaleInfo bKSaleInfoField;
        
        private System.Nullable<bool> batchShouldCloseField;
        
        private bool batchShouldCloseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantId
        {
            get
            {
                return this.merchantIdField;
            }
            set
            {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReferenceTransactionId
        {
            get
            {
                return this.referenceTransactionIdField;
            }
            set
            {
                this.referenceTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResultDetail
        {
            get
            {
                return this.resultDetailField;
            }
            set
            {
                this.resultDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Item[] CustomItems
        {
            get
            {
                return this.customItemsField;
            }
            set
            {
                this.customItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public InstallmentItem[] InstallmentTable
        {
            get
            {
                return this.installmentTableField;
            }
            set
            {
                this.installmentTableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CampaignItem", IsNullable=false)]
        public CampaignInfo[] CampaignResult
        {
            get
            {
                return this.campaignResultField;
            }
            set
            {
                this.campaignResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public MerchantCampaignResult MerchantCampaignResult
        {
            get
            {
                return this.merchantCampaignResultField;
            }
            set
            {
                this.merchantCampaignResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AuthCode
        {
            get
            {
                return this.authCodeField;
            }
            set
            {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string HostDate
        {
            get
            {
                return this.hostDateField;
            }
            set
            {
                this.hostDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Rrn
        {
            get
            {
                return this.rrnField;
            }
            set
            {
                this.rrnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> PointLosts
        {
            get
            {
                return this.pointLostsField;
            }
            set
            {
                this.pointLostsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointLostsSpecified
        {
            get
            {
                return this.pointLostsFieldSpecified;
            }
            set
            {
                this.pointLostsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TerminalNo
        {
            get
            {
                return this.terminalNoField;
            }
            set
            {
                this.terminalNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> PointAmount
        {
            get
            {
                return this.pointAmountField;
            }
            set
            {
                this.pointAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointAmountSpecified
        {
            get
            {
                return this.pointAmountFieldSpecified;
            }
            set
            {
                this.pointAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> PointCode
        {
            get
            {
                return this.pointCodeField;
            }
            set
            {
                this.pointCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointCodeSpecified
        {
            get
            {
                return this.pointCodeFieldSpecified;
            }
            set
            {
                this.pointCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> GainedPoint
        {
            get
            {
                return this.gainedPointField;
            }
            set
            {
                this.gainedPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GainedPointSpecified
        {
            get
            {
                return this.gainedPointFieldSpecified;
            }
            set
            {
                this.gainedPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<decimal> TotalPoint
        {
            get
            {
                return this.totalPointField;
            }
            set
            {
                this.totalPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPointSpecified
        {
            get
            {
                return this.totalPointFieldSpecified;
            }
            set
            {
                this.totalPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> CurrencyAmount
        {
            get
            {
                return this.currencyAmountField;
            }
            set
            {
                this.currencyAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyAmountSpecified
        {
            get
            {
                return this.currencyAmountFieldSpecified;
            }
            set
            {
                this.currencyAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> CurrencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyCodeSpecified
        {
            get
            {
                return this.currencyCodeFieldSpecified;
            }
            set
            {
                this.currencyCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<decimal> VftAmount
        {
            get
            {
                return this.vftAmountField;
            }
            set
            {
                this.vftAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VftAmountSpecified
        {
            get
            {
                return this.vftAmountFieldSpecified;
            }
            set
            {
                this.vftAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<decimal> SurchargeAmount
        {
            get
            {
                return this.surchargeAmountField;
            }
            set
            {
                this.surchargeAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SurchargeAmountSpecified
        {
            get
            {
                return this.surchargeAmountFieldSpecified;
            }
            set
            {
                this.surchargeAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<int> NumberOfInstallments
        {
            get
            {
                return this.numberOfInstallmentsField;
            }
            set
            {
                this.numberOfInstallmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfInstallmentsSpecified
        {
            get
            {
                return this.numberOfInstallmentsFieldSpecified;
            }
            set
            {
                this.numberOfInstallmentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<int> InstallmentCount
        {
            get
            {
                return this.installmentCountField;
            }
            set
            {
                this.installmentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstallmentCountSpecified
        {
            get
            {
                return this.installmentCountFieldSpecified;
            }
            set
            {
                this.installmentCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<int> RecurringInstallmentCount
        {
            get
            {
                return this.recurringInstallmentCountField;
            }
            set
            {
                this.recurringInstallmentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurringInstallmentCountSpecified
        {
            get
            {
                return this.recurringInstallmentCountFieldSpecified;
            }
            set
            {
                this.recurringInstallmentCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string ECI
        {
            get
            {
                return this.eCIField;
            }
            set
            {
                this.eCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> ThreeDSecureType
        {
            get
            {
                return this.threeDSecureTypeField;
            }
            set
            {
                this.threeDSecureTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThreeDSecureTypeSpecified
        {
            get
            {
                return this.threeDSecureTypeFieldSpecified;
            }
            set
            {
                this.threeDSecureTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<int> TransactionDeviceSource
        {
            get
            {
                return this.transactionDeviceSourceField;
            }
            set
            {
                this.transactionDeviceSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDeviceSourceSpecified
        {
            get
            {
                return this.transactionDeviceSourceFieldSpecified;
            }
            set
            {
                this.transactionDeviceSourceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<int> Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationSpecified
        {
            get
            {
                return this.locationFieldSpecified;
            }
            set
            {
                this.locationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<int> DeviceType
        {
            get
            {
                return this.deviceTypeField;
            }
            set
            {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceTypeSpecified
        {
            get
            {
                return this.deviceTypeFieldSpecified;
            }
            set
            {
                this.deviceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Tavv
        {
            get
            {
                return this.tavvField;
            }
            set
            {
                this.tavvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<int> BatchNo
        {
            get
            {
                return this.batchNoField;
            }
            set
            {
                this.batchNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BatchNoSpecified
        {
            get
            {
                return this.batchNoFieldSpecified;
            }
            set
            {
                this.batchNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string PanCode
        {
            get
            {
                return this.panCodeField;
            }
            set
            {
                this.panCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<decimal> TLAmount
        {
            get
            {
                return this.tLAmountField;
            }
            set
            {
                this.tLAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TLAmountSpecified
        {
            get
            {
                return this.tLAmountFieldSpecified;
            }
            set
            {
                this.tLAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=36)]
        public LimitSearchResult[] LimitSearchResults
        {
            get
            {
                return this.limitSearchResultsField;
            }
            set
            {
                this.limitSearchResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=37)]
        public PlanSearchResult[] PlanSearchResults
        {
            get
            {
                return this.planSearchResultsField;
            }
            set
            {
                this.planSearchResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string HostSubMerchantId
        {
            get
            {
                return this.hostSubMerchantIdField;
            }
            set
            {
                this.hostSubMerchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string Identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<int> MerchantType
        {
            get
            {
                return this.merchantTypeField;
            }
            set
            {
                this.merchantTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantTypeSpecified
        {
            get
            {
                return this.merchantTypeFieldSpecified;
            }
            set
            {
                this.merchantTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string HostResultCode
        {
            get
            {
                return this.hostResultCodeField;
            }
            set
            {
                this.hostResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=42)]
        public BKAccount[] BKAccounts
        {
            get
            {
                return this.bKAccountsField;
            }
            set
            {
                this.bKAccountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public BKSaleInfo BKSaleInfo
        {
            get
            {
                return this.bKSaleInfoField;
            }
            set
            {
                this.bKSaleInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public System.Nullable<bool> BatchShouldClose
        {
            get
            {
                return this.batchShouldCloseField;
            }
            set
            {
                this.batchShouldCloseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BatchShouldCloseSpecified
        {
            get
            {
                return this.batchShouldCloseFieldSpecified;
            }
            set
            {
                this.batchShouldCloseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class CustomInstallment
    {
        
        private string dateField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class CustomInstallments
    {
        
        private CustomInstallment[] customInstallmentField;
        
        private System.Nullable<int> maturityPeriodField;
        
        private System.Nullable<int> frequencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomInstallment", Order=0)]
        public CustomInstallment[] CustomInstallment
        {
            get
            {
                return this.customInstallmentField;
            }
            set
            {
                this.customInstallmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> MaturityPeriod
        {
            get
            {
                return this.maturityPeriodField;
            }
            set
            {
                this.maturityPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Frequency
        {
            get
            {
                return this.frequencyField;
            }
            set
            {
                this.frequencyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface TransactionWebServicesSoapChannel : VakifBankVPosTest.TransactionWebServicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class TransactionWebServicesSoapClient : System.ServiceModel.ClientBase<VakifBankVPosTest.TransactionWebServicesSoap>, VakifBankVPosTest.TransactionWebServicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TransactionWebServicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TransactionWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), TransactionWebServicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionWebServicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TransactionWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionWebServicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TransactionWebServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VakifBankVPosTest.VposResponse> ExecuteVposRequestAsync(VakifBankVPosTest.VposRequest vposRequest)
        {
            return base.Channel.ExecuteVposRequestAsync(vposRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TransactionWebServicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TransactionWebServicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TransactionWebServicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://onlineodemetest.vakifbank.com.tr:4443/VposService/TransactionServices.asm" +
                        "x");
            }
            if ((endpointConfiguration == EndpointConfiguration.TransactionWebServicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://onlineodemetest.vakifbank.com.tr:4443/VposService/TransactionServices.asm" +
                        "x");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TransactionWebServicesSoap,
            
            TransactionWebServicesSoap12,
        }
    }
}
